# Generated by Django 2.2.14 on 2020-11-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='estudiantes', to='estudiantes.Estudiante'),
        ),
    ]
