# Generated by Django 2.2.14 on 2020-11-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clase_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='clases', to='estudiantes.Estudiante'),
        ),
    ]
