# Generated by Django 2.2.14 on 2020-12-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0003_auto_20201123_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clases', models.ManyToManyField(related_name='profesor', to='clases.Clase')),
            ],
        ),
    ]
